// do not include in source control
module.exports = {
    userName : 'Partner\\uat.geor.marioncu',
    passWord : 'georgianPassword',
    grantType : 'password',
    loginUrl: 'https://etms.uat.ocas.ca/api/auth/login',
    transcriptsNoResponseUrl : 'https://etms.uat.ocas.ca/api/transcripts/no_response',
    transcriptDetailUrl : 'https://etms.uat.ocas.ca/api/transcripts/',
    requestsNoResponseUrl : 'https://etms.uat.ocas.ca/api/transcriptrequests/no_response',
    transcriptRequestUrl : 'https://etms.uat.ocas.ca/api/transcriptrequests/',
    sendTranscriptUrl : 'https://etms.uat.ocas.ca/api/transcriptrequests/',
    transcriptAcknowledgmentUrl: "https://etms.uat.ocas.ca/api/transcripts/:requestId/acknowledgment",
    transcriptAcknowledgmentPersonElements: [
        "SchoolAssignedPersonID",
        "SIN",
        "NSN",
        "AgencyAssignedID",
        "AgencyIdentifier",
        "RecipientAssignedID",
        "SSN",
        "PartialSSN",
        "Birth",
        "Name",
        "AlternateName",
        "Contacts",
        "Gender",
        "Deceased",
        "Language",
        "NoteMessage"
    ],
    ocasAcknowledgmentDocumentProcessCode: "TEST",
    ddpUrl: 'wss://api.georgiancollege.ca/transcript/websocket',
    ddpUser : 'ddpUsername',
    ddpPassword : 'ddpPassword',
    jobCollectionName: 'student-transcript',
    dbConfig : {
        user: 'georgianUser',
        password: 'georgianUserPassword',
        connectString: 'testrac01-vip.admin.georgianc.on.ca/gsb1',
        poolMax: 20,
        poolMin: 2,
        poolIncrement: 2,
        poolTimeout: 10
    },
    appxtenderURL: 'http://tsdocmgmt01/AppXtenderServices/AxServicesInterface.asmx?WSDL',
    appxtenderUser: 'xxxxx',
    appxtenderPass: 'xxxxx',
    appxtenderDSN: 'GGGG',
    appxtenderAppId: '522',
    // The following must point to the same shared filesystem path
    appxtenderFilePath: "\\\\badocmgmt01\\Documentum/incoming_transcripts/",
    localFilePath: "\\\\badocmgmt01\\Documentum/incoming_transcripts/"
}