module.exports = {
    userName : 'xxxxxxxxxxxxxxxxxxxxxxxx',
    passWord : 'xxxxxxxxxxxxx',
    grantType : 'xxxxxxxxxxxxx',
    loginUrl: 'https://etms.uat.ocas.ca/api/auth/login',
    transcriptsNoResponseUrl : 'https://etms.uat.ocas.ca/api/transcripts/no_response',
    transcriptDetailUrl : 'https://etms.uat.ocas.ca/api/transcripts/',
    requestsNoResponseUrl : 'https://etms.uat.ocas.ca/api/transcriptrequests/no_response',
    transcriptRequestUrl : 'https://etms.uat.ocas.ca/api/transcriptrequests/',
    sendTranscriptUrl : 'https://etms.uat.ocas.ca/api/transcriptrequests/',
    transcriptToHtmlURL: "https://xxxxxx.com/transformdoc",
    ddpHost : '',
    ddpPort : ' ',
    ddpUser : 'xxxxxxxxxxxxxxxxx',
    ddpPassword : 'xxxxxxxxxxxxx',
    oracleUserId        : "********",
    oraclePassword      : "*******",
    oracleConnectString : "****************************************",
    appxtenderURL: "**",
    appxtenderUser: "**",
    appxtenderPass: "**",
    appxtenderDSN: "**",
    appxtenderAppId: "**",
    appxtenderFilePath: "c:/apps/local/transcript/docs/"
}